services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: pinmonkey
      POSTGRES_PASSWORD:
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: dev
    command: php artisan serve --host=0.0.0.0 --port=9050
    ports:
      - "9050:9050"
    security_opt:
      - apparmor=unconfined
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: "base64:"
      DB_CONNECTION: phsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: pinmonkey
      DB_PASSWORD:
    volumes:
      - .:/var/www
    depends_on:
      - db

  test:
    build:
      context: .
      target: test
    environment:
      APP_ENV: testing
      APP_KEY: "base64:"
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

  prod:
    build:
      context: .
      target: prod
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    ports:
      - "9000:9000"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: "base64:"
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: pinmonkey
      DB_PASSWORD:

volume:
  db_data:
